## Wave 3 Texts

Intend to analyze the responses of humans and AI in several ways:
- Lexical Analysis
- Semantic Analysis
- Analysis of Lexical and Semantic grouped within human/model, question category, question

In [10]:
# %pip install openai plotly seaborn statsmodels

Requirement already satisfied: openai in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (0.28.1)
Collecting plotly
  Downloading plotly-5.18.0-py3-none-any.whl (15.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 80.2 MB/s eta 0:00:0000:0100:01
Collecting seaborn
  Downloading seaborn-0.13.0-py3-none-any.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 23.5 MB/s eta 0:00:00
Collecting statsmodels
  Downloading statsmodels-0.14.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 112.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: requests>=2.20 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from openai) (2.31.0)
Requirement already satisfied: tqdm in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from openai) (4.65.0)
Requirement already satisfied: aiohttp in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from openai) (3.8.6)
Collecting tenacity>=6.2.0 (from plotly)
  Downloading tenacity-8.2.3-py3-none-any.whl (24 kB)
Requirement already satisfied: packaging in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from plotly) (23.0)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from seaborn) (1.25.0)
Requirement already satisfied: pandas>=1.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from seaborn) (3.7.1)
Requirement already satisfied: scipy!=1.9.2,>=1.4 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from statsmodels) (1.10.1)
Collecting patsy>=0.5.2 (from statsmodels)
  Downloading patsy-0.5.3-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.8/233.8 kB 22.6 MB/s eta 0:00:00
Requirement already satisfied: contourpy>=1.0.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (4.40.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (3.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.20->openai) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.20->openai) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests>=2.20->openai) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from aiohttp->openai) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from aiohttp->openai) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from aiohttp->openai) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from aiohttp->openai) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from aiohttp->openai) (1.3.1)
Installing collected packages: tenacity, patsy, plotly, statsmodels, seaborn
Successfully installed patsy-0.5.3 plotly-5.18.0 seaborn-0.13.0 statsmodels-0.14.0 tenacity-8.2.3
Note: you may need to restart the kernel to use updated packages.

In [3]:
# load necessary packages
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

In [4]:
dfl = pd.read_csv('./data/wave 3/wave 3 response evals - long v4 - with qr text and w2 actuals.csv')

In [5]:
# construct SDO_ variable that is the average of SDO and reverse-coded SDO_R
dfl['w3_rated_SDO_'] = (dfl['w3_rated_SDO'] + (6 - dfl['w3_rated_SDO_R'])) / 2

In [6]:
modelSort = ['human',
             'fb-opt-1.3b','fb-opt-iml-1.3b',
             'gpt-2','gpt-3','ChatGPT','gpt-4']
# convert model to categorical dtype
from pandas.api.types import CategoricalDtype
dfl['model'] = dfl['model'].astype(CategoricalDtype(categories=modelSort, ordered=False))
dfl.model.dtype

CategoricalDtype(categories=['human', 'fb-opt-1.3b', 'fb-opt-iml-1.3b', 'gpt-2', 'gpt-3',
                  'ChatGPT', 'gpt-4'],
, ordered=False)

In [7]:
dfl.columns

Index(['w3_rater_ResponseId', 'w3_rater_StartDate',
       'w3_rater_LocationLatitude', 'w3_rater_LocationLongitude',
       'w3_rater_gender', 'w3_rater_age', 'w3_rater_height', 'w3_rater_weight',
       'w3_rater_race', 'w3_rater_employ', 'w3_rater_income', 'w3_rater_educ',
       'w3_rater_poli_affil', 'w3_rater_voted', 'w3_rater_big5_extra',
       'w3_rater_big5_agree', 'w3_rater_big5_conc', 'w3_rater_big5_neuro',
       'w3_rater_big5_open', 'w3_rater_SDO_R', 'w3_rater_SDO', 'Rid', 'Index',
       'w3_rated_gender', 'w3_rated_age', 'w3_rated_height', 'w3_rated_weight',
       'w3_rated_race', 'w3_rated_income_19', 'w3_rated_education',
       'w3_rated_conservative', 'w3_rated_voted', 'w3_rated_extravert',
       'w3_rated_agreeable', 'w3_rated_concientious', 'w3_rated_neurotic',
       'w3_rated_open', 'w3_rated_SDO_R', 'w3_rated_SDO', 'w3_rated_trust',
       'w3_rated_interact', 'model', 'index', 'qcat', 'qid', 'question',
       'response', 'w2_ResponseId', 'w3_rated_SDO_', 'w2_actual_SDO',
       'w2_actual_open', 'w2_actual_concientious', 'w2_actual_extravert',
       'w2_actual_agreeable', 'w2_actual_neurotic', 'w2_actual_gender',
       'w2_actual_income', 'w2_actual_age', 'w2_actual_race',
       'w2_actual_education', 'w2_actual_conservative', 'w2_actual_weight',
       'w2_actual_height'],
      dtype='object')

In [11]:
# create ada embeddings for all the responses
import json
import openai
from openai.embeddings_utils import (
    get_embedding, cosine_similarity,
    tsne_components_from_embeddings,
    chart_from_components,
)
import os

In [12]:
dfl.shape

(38605, 63)

In [13]:
# load config
with open(r'config.json') as config_file:
    config_details = json.load(config_file)
    
# Setting up the deployment name
deployment_name = config_details['EMBEDDINGS_MODEL']

# This is set to `azure`
openai.api_type = "azure"

# The API key for your Azure OpenAI resource.
openai.api_key = config_details["OPENAI_API_KEY"]

# The base URL for your Azure OpenAI resource. e.g. "https://<your resource name>.openai.azure.com"
openai.api_base = config_details['OPENAI_API_BASE']

# Currently OPENAI API have the following versions available: 2022-12-01
openai.api_version = config_details['OPENAI_API_VERSION']

In [29]:
# test embedding on subset of data
dfs = dfl[['model', 'index', 'qcat', 'qid', 'question','response',]].head()

In [11]:
dfs

,model,index,qcat,qid,question,response
0,fb-opt-1.3b,1,1,1,What is your opinion on abortion?,"I agree that abortion is a serious matter, but..."
1,fb-opt-1.3b,2,1,1,What is your opinion on abortion?,"I have no opinion, but I am very concerned wit..."
2,fb-opt-1.3b,3,1,1,What is your opinion on abortion?,"If you're planning on having kids, have them. ..."
3,fb-opt-1.3b,4,1,1,What is your opinion on abortion?,I don't think you can say that abortion should...
4,fb-opt-1.3b,5,1,1,What is your opinion on abortion?,"I have no opinion, but I am very concerned wit..."

In [30]:
dfs['response_ada_v2'] = dfs["response"].apply(lambda x : get_embedding(x, engine = 'text-embedding-ada-002')) # engine should be set to the deployment name you chose when you deployed the text-embedding-ada-002 (Version 2) model

In [34]:
dfs[['response','response_ada_v2']].head()

,response,response_ada_v2
0,"I agree that abortion is a serious matter, but...","[-0.02235282212495804, -0.03829408064484596, -..."
1,"I have no opinion, but I am very concerned wit...","[-0.027138056233525276, -0.025159239768981934,..."
2,"If you're planning on having kids, have them. ...","[-0.011410890147089958, -0.01900525577366352, ..."
3,I don't think you can say that abortion should...,"[-0.008020703680813313, -0.02725287526845932, ..."
4,"I have no opinion, but I am very concerned wit...","[-0.027138056233525276, -0.025159239768981934,..."

In [56]:
# try collecting embeddings for all responses
# collect embeddings for all human responses
hdfl = dfl[dfl['model'] == 'human']
hdfl.shape

(5513, 63)

In [57]:
hdfl['response_ada_v2'] = hdfl["response"].apply(
    lambda x : get_embedding(
        x, 
        engine = 'text-embedding-ada-002')) # engine should be set to the deployment name you chose when you deployed the text-embedding-ada-002 (Version 2) model

RetryError: RetryError[<Future at 0x1fcc724fbe0 state=finished raised RateLimitError>]

(38605,)

In [66]:
L

38605

In [14]:
response_list = dfl['response'].tolist()
len(response_list)

38605

In [77]:
response_list[577]

'Police brutality is an egregious violation of the rights of individuals and should not be tolerated in any form. The police are responsible for protecting and serving the public, and any act of brutality is a violation of that duty. There needs to be greater accountability and transparency in law enforcement, and those found to have engaged in brutality should be held to the highest standards of justice.'

In [15]:
import datetime
st = datetime.datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
print(st)

2023-11-01-10-10-04

In [16]:
import time 
import datetime
st = datetime.datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
print(st)

embed_list = []
i = 0
response_list = dfl['response'].tolist()
L = len(response_list)
while i < L:
    r = response_list[i]
    if i % 100 == 0: print(f'{i}: {r}')
    try:
        embed = get_embedding(r, engine = 'text-embedding-ada-002')
        embed_list.append(embed)
        i += 1 # increment counter only if successful
    except Exception as e:
        print(e)
        time.sleep(2)
    time.sleep(0.05)

embeddings = np.array(embed_list)
print(embeddings.shape)
np.save(f'./data/wave 3/response_embeddings-{st}.npy', embeddings)

2023-11-01-10-11-05
0: I agree that abortion is a serious matter, but I am also a pro-choice person, and not a pro-abortion person.
I think that women should be able to make decisions for themselves about their bodies, and that the government should not have a say in it.
Obviously, there are some cases where women should have the right to have an abortion.
100: The question is not whether one should be pro-life or pro-choice. The question is whether one should be pro-life or pro-choice, or pro-pro-life or pro-pro-choice."
This is not a choice. It is a decision.
200: A fetus typically becomes viable at 24 weeks of gestation, although it can vary depending on the circumstances.
300: My understanding of the issue of abortion is that it is a highly contentious and divisive issue that is deeply personal and varies depending on individual beliefs and values. I believe that women should have the right to choose whether or not to terminate a pregnancy and that the decision should be made between a woman and her healthcare provider. I also recognize that there are moral, ethical.
400: Yes, but the question is what defines life?
I don't see how a fetus is a person because it's not conscious.
RetryError[<Future at 0x7f3c5837c100 state=finished raised RateLimitError>]
500: I believe it is very real, and I am sure of it.  I do believe there is plenty of evidence to support this, but I also think the evidence is circumstantial, circumstantial as in the amount of evidence is so small it is almost impossible to prove.  But I also believe there is a pattern of fraud happening.
600: I used to be anti-vaccination but then I became an avid anti-vaccinationist and have been pretty much against them ever since.
It's not due to a scientific or practical reason, it's due to religious beliefs.
The vast majority of parents can't be bothered to ask the doctors/nurses/etc. what the right thing to do is.
700: It's the same thing we tell each other every day...
 You can't stop all of the shootings.  I'm not sure you can stop them all, but you can make sure that they are less deadly.

 As in, "If you can't stop the bad guns, you should get rid of the good guns.
RetryError[<Future at 0x7f3c5837ca90 state=finished raised RateLimitError>]
800: Well, the father is responsible for the child's well-being.  What he does with that responsibility is up to him and the child.  His job is to take care of the child and provide basic necessities, whether it's clothing, food, medical care, and so on, since what is in his control is his life.
900: This is a very interesting topic, but I'm not sure it's best to have a poll asking people to say that they trust the results of the 2020 elections.
The poll has a couple of flaws. First, it doesn't ask a single question about trust in the election outcome. Instead, it asks people to answer some questions about the people and institutions that will decide the outcome.
1000: If anyone has any insight as to why or why not, I would love to hear it!  I am an attorney and used to teach law at a law school.  My heart goes out to the mothers and fathers of the children that are caught in this mess.  I know they are in pain.  I am also in pain.
1100: Controversial issues can affect one's daily life in a variety of ways. Here are some examples:
1. They can create stress and anxiety: If you are someone who cares deeply about social or political issues, you may find yourself feeling stressed or anxious when you read the news or have conversations with people who hold opposing views. This can affect your mood, your sleep.
1200: I believe that the government should not have control over a woman's reproductive health. It is a personal decision that should be left up to the individual to determine what is best for their own life. The government should not have the ability to dictate what a woman can or cannot do with her own body.
RetryError[<Future at 0x7f3c5837d000 state=finished raised RateLimitError>]
1300: One of the most controversial issues facing the United States this year has been the ongoing debate over immigration reform. There has been a great deal of disagreement over how to handle the influx of immigrants from Central America, how to deal with those already in the country illegally, and how to protect US borders.
1400: This is a very interesting question. Personally, I'm not really that bothered that the NSA is listening to my phone calls and emails. What I am bothered by is how the government can arbitrarily interpret what constitutes evidence or a threat and then prosecute a person for what they consider to be "insulting" them.
RetryError[<Future at 0x7f3c5837c5b0 state=finished raised RateLimitError>]
1500: I am very concerned about many of the problems we are facing today. We have a lot of problems in our country. Problems of poverty, problems of unemployment, problems of a very large number of people not being able to get their education, being unable to get good jobs, and all of this is having a negative effect on our society.
1600: I think abortion is a terrible thing. I also think the arguments for and against are both good arguments. It is not the right of a government to control the lives of its citizens or to force someone to do anything.
I also think that the right to abortion is a right that should be protected by the constitution, and should not be subject to judicial review by politicians or citizens.
1700: I don't care so much, but they should invest as much money as possible in their cause.
1800: I think it's a sad sad thing to happen, but in a way it's good for society because it's not happening anymore.  I believe that a woman has the right to choose and she has the ability to do it, even if I don't like it.  I think that's why Roe v Wade was so important, because it gave women some of the right to choose.
1900: I think voting is a privilege and those who choose not to vote are giving up their privilege.
2000: I think it's the fact that we have a lot of children who aren't being taught what's right, what's wrong. They're being taught not to be gay, or not to be a woman, or whatever it is. And we have to teach them to be adults and be responsible for themselves.
2100: I am going to be a little more cautious than usual.  I really like the idea of a woman's right to choose, and I think it is important that the law is enforced and the people are informed.  I think they are right to put the onus on the woman to make the decision, but I don't think it should be overturned.
RetryError[<Future at 0x7f3c5837dba0 state=finished raised RateLimitError>]
2200: This is the first time I have seen a comment that is so blatantly false.
The first time I ever saw a comment that was so blatantly false was when I was in 6th grade and a few of my friends and I were hanging out. When we weren't hanging out, we were in my classroom, learning our lessons. There is no way that this is true.
2300: I think that the time has come for an outright ban on all weapons. There should be no exceptions or loopholes. I realize the American people do not want to live in a world where everything is armed to the teeth, but it is necessary.
2400: My opinion is that life begins in the womb at conception. This is based on the scientific understanding that life is created when a sperm fertilizes an egg, forming a unique, living organism with its own DNA.
2500: I think there are a number of factors that could lead someone to choose giving birth rather than having an abortion. Here are a few:
- Financial considerations: If someone is worried about the financial cost of having a child, they might consider abortion. However, if they find that they're able to make ends meet with a child, they might choose to have the baby.
RetryError[<Future at 0x7f3c5837e110 state=finished raised RateLimitError>]
2600: In my own opinion to this is that they used make it a choice and readily available for the people that need it. And lack of access to this can cause damage if that person approach it in wrong way
RetryError[<Future at 0x7f3c5837d090 state=finished raised RateLimitError>]
2700: I am a nurse and have been vaccinated since before I was born.  I am currently taking a new medication that may cause my immune system to produce antibodies and I am worried that if I go to bed without them, that I will not be able to fight off the infection.  Who are you going to believe - the doctor or the vaccine?
2800: Yes, I believe in climate change. There is overwhelming scientific evidence to support the fact that climate change is real and caused by human activities.
2900: If the system can't handle it, what do you think it should do?
3000: I feel very strongly that if you want to make a change in a world, you have to make it in the US. There's a certain amount of self-righteousness and a certain amount of arrogance in the US. But I think we can make a big difference in the US. People need to realize that we are the largest, richest country in the world.
3100: It was the right decision. The decision was correct in what it tried to accomplish. Unfortunately, the decision was not unanimous.
RetryError[<Future at 0x7f3c5837e7a0 state=finished raised RateLimitError>]
3200: The answer to this question is highly subjective and will depend on the laws and regulations of the particular jurisdiction in which the abortion is being sought. It is not possible to give a definitive answer as to the maximum number of weeks that abortion should be available.
RetryError[<Future at 0x7f3c5837ec50 state=finished raised RateLimitError>]
3300: The abortion issue is complex and deeply personal, and my view is that it should be a decision made with care and thoughtfulness by individuals and their families. Ultimately, I believe that the decision should be left to the individual and should not be subject to the control of the government or any other outside force.
3400: I can't imagine not being against them.
If someone doesn't like that a baby has its head cut off in the womb, I see no reason to argue.
3500: Yes No Do you support abortion in all circumstances?
3600: The right to control one's own reproductive health and choices is widely considered to be a fundamental aspect of women's autonomy and bodily autonomy. Women should have the ability to make informed decisions about their reproductive health, including decisions about contraception and pregnancy, without interference from others. This can empower women to shape their own lives and future, and to participate fully in social, economic, and political life.

There are many factors that can impact women's reproductive health and choices, including access to comprehensive reproductive health information and services, cultural and social norms, and economic and political factors. Ensuring that women have control over their reproductive health and choices is essential for promoting gender equality and empowering women to lead fulfilling lives.
3700: If you don't believe in God, do you think there is anything worse than the torturing of people in hell?

 If you think Jesus is Lord and Savior of the world, why would you torture anyone?
3800: Throw my shoe at their head if provided the opportunity
3900: The acceptability of abortion depends on individual beliefs, cultural values, and legal frameworks. Some situations where people might consider abortion acceptable include:
1. When the mother's life or health is at risk: If continuing the pregnancy poses a significant risk to the mother's physical or mental health, some people may consider it acceptable to have an abortion.
4000: Because God doesn’t exist.
RetryError[<Future at 0x7f3c5837c670 state=finished raised RateLimitError>]
4100: 3. If you believe that abortion should be illegal in all states, would you be willing to support/adopt or take on an unwanted child from someone who cannot get an abortion today? If no, why?
4200: I believe yes.
4300: How do you feel about same-sex marriage??
4400: If you would like to continue to participate, please answer the following question on a scale of 1-10 with one being Totally disagree to ten being totally agree: Should the state tax people who have an abortion?
4500: Abortion is used on a frequent basis for several reasons, often tied to individual circumstances, personal beliefs, and societal factors. Some of these reasons include:
1. Lack of access to contraception: In many areas, people may not have easy access to affordable and effective birth control methods. This can lead to unintended pregnancies, which may result in individuals seeking abortions.
4600: I believe that life begins at conception.
RetryError[<Future at 0x7f3c5837e680 state=finished raised RateLimitError>]
4700: Because they are racists and want to rule the world.
4800: I am against the death penalty, but I am also a Christian. I think there are some very religious people who should be punished in the same way for their beliefs.
Do you think that people are too easily influenced by their religious leaders and should be punished for not being 100% faithful, even if you think their leader is an idiot?
RetryError[<Future at 0x7f3c5837eb60 state=finished raised RateLimitError>]
4900: Do you mean what I think about a political situation in the world? This is more of a civil right issues, but I think that the Supreme Court ruling to overturn Roe is devastating to all women of breeding age, all men capable of reproduction, and anyone and everyone in their lives. The clawback of reproductive rights in many states basically takes away the right to self-determination -- how one wishes to live, who they aspire to be, and basically, the entire meaning of their existence.
5000: My thoughts on gun control are that it is an important issue that needs to be addressed in order to keep our communities safe. I believe that all legal gun owners should be subject to thorough background checks and that any firearms should be stored and used responsibly.
5100: It is not accurate to say that all Republicans like to discredit science. However, there are a few reasons why some Republicans might be perceived to discredit scientific findings or be skeptical of scientific consensus:
1. Political ideology: Some Republicans have a political ideology that emphasizes limited government involvement, deregulation, and individual liberty.
RetryError[<Future at 0x7f3c5837d420 state=finished raised RateLimitError>]
5200: Illegal immigration is a complex issue that requires careful consideration. Without comprehensive immigration reforms, it will likely remain a contentious issue for years to come. It is important to remember that people who immigrate illegally are often driven to do so out of desperation and should be treated with empathy and respect. It is also essential to ensure that our immigration policies are both fair and effective.
5300: Yes, I do, it's a problem, I think it's mainly (sic) because we're burning too much coal.
5400: I think that abortion is a complex issue that involves a range of ethical, moral, and practical considerations. While I believe that women should have the right to make decisions about their own bodies and reproductive health, I also recognize that abortion can be a difficult and painful choice that is not taken lightly.
5500: Because they have sensible gun laws, and less of their history about being an individual and doing what you want at the cost of how it affects others. Plus, bloodthirsty-ness as been part of the US's history since day one.
5600: No, I believe in abortion in only rare cases
5700: People who have differing viewpoints than others get worked up and feel the urge to commit violent crimes.
RetryError[<Future at 0x7f3c5837eb30 state=finished raised RateLimitError>]
5800: The right to free speech doesn't exist until someone is actually harmed by that speech.
It's just like the right to personal freedom of speech.
5900: Respecting a coworker's they/them pronouns is important for several reasons:
1. Demonstrates respect and inclusion: Using someone's preferred pronouns acknowledges their identity and shows that you accept and respect them for who they are. This creates an inclusive and supportive work environment, which is essential for everyone's well-being and productivity.
RetryError[<Future at 0x7f3c5837ed10 state=finished raised RateLimitError>]
6000: Inflation has had a significant impact on my life recently. Prices of basic goods and services, such as groceries and fuel, have risen steadily over the past year, making it more difficult to keep up with costs. Additionally, as inflation rises so do interest rates, meaning that borrowing money becomes more expensive for both businesses and individuals, leading to a decrease in purchasing power.
RetryError[<Future at 0x7f3c5837eb00 state=finished raised RateLimitError>]
6100: I would feel incredibly frustrated and powerless. Voting is an important civic duty that allows individuals to have a voice in the political process and to have a say in who is elected to represent them. Losing the right to vote would be a serious blow to my sense of agency and my belief in democracy as a fair and just system.
6200: I fully support abortion in any case for any reason.
6300: This is a complicated issue that can be approached from a variety of perspectives. Ultimately, the decision about whether or not to grant cash reparations to African Americans rests with the government. Supporters of reparations point to the legacy of slavery and systemic racism in the United States, arguing that reparations are necessary to help address the economic and social inequities that remain today.
6400: I would say that I am more left leaning.
6500: Abortion is a complex and controversial issue with ethical, moral, legal, and religious considerations. The question of whether abortion is right is subjective and depends on individual beliefs and values. Some people argue that abortion can be considered right in certain circumstances, such as:
6600: I don't know him very much but from what I've seen, I don't like him.
RetryError[<Future at 0x7f3c5837ead0 state=finished raised RateLimitError>]
6700: I am pro choice of some within a certain time frame of pregnancy.
6800: I believe that an assault rifle ban is a sensible measure to help prevent mass shootings and protect people from the potential of gun violence. Assault rifles are designed for military use and have no place in civilian life. Furthermore, studies have shown that states and countries with stricter gun control laws have lower rates of gun violence and mass shootings.
6900: They should know their worth and begin to look for a better paid position in their profession elsewhere.
7000: 1. Maintain professionalism: Always maintain a professional attitude, even if your manager is difficult to deal with. Avoid engaging in gossip, personal attacks, or other unprofessional behavior.
2. Communication: Open and clear communication is essential in dealing with a difficult manager. Make an effort to understand their expectations and communicate your concerns or issues calmly and clearly.
7100: What's your favorite thing?  What's your least favorite thing?
RetryError[<Future at 0x7f3c5837e710 state=finished raised RateLimitError>]
7200: Everything is fine I don't feel this way
7300: I think that it would be hard to find somebody who makes as good a lot of money as I do, but because my work is so high quality and takes a long time, I think that I have not done as much as I could have, so I think it would be hard for anyone to do what I do. But if you work at it, you can do it.
RetryError[<Future at 0x7f3c5837c760 state=finished raised RateLimitError>]
7400: My thought process on work and personal balance in everyday life is that it is important to have a proper balance between the two. It is important to ensure that you are making time for yourself and your family, while still being productive and efficient with your work.

In [62]:
i

356

In [41]:
# test saving and reloading
# remove the embedding column
dfs_embeddings = dfs['response_ada_v2']
# dfs = dfs.drop(columns=['response_ada_v2'])

# save the embeddings
np_df_embeddings = np.array(dfs_embeddings.to_list())
np.save('./data/wave 3/response_embeddings.npy', np_df_embeddings)
# save the csv
# dfs.to_csv('./data/wave 3/dfs-test.csv', index=False)

In [46]:
np_df_embeddings = np.load('./data/wave 3/response_embeddings.npy')

In [51]:
np_df_embeddings

array([[-0.02235282, -0.03829408, -0.01292331, ..., -0.01967299,
        -0.01066925, -0.04012238],
       [-0.02713806, -0.02515924,  0.00655965, ..., -0.00756833,
        -0.01453274, -0.04528149],
       [-0.01141089, -0.01900526, -0.00268994, ..., -0.01612997,
         0.02228025, -0.01765142],
       [-0.0080207 , -0.02725288,  0.00807075, ..., -0.01037937,
         0.01024173, -0.03165738],
       [-0.02713806, -0.02515924,  0.00655965, ..., -0.00756833,
        -0.01453274, -0.04528149]])

In [26]:
dfs = pd.read_csv('./data/wave 3/dfs-test.csv')

In [52]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def get_mean_cosine_sim(dfCol):
    if type(dfCol) == np.ndarray:
        vectors = dfCol
    # convert vectors column to numpy array
    else:
        vectors = np.array(dfCol.tolist())

    # calculate cosine similarity between all pairs of vectors
    cos_sim = cosine_similarity(vectors)

    # calculate average cosine similarity between all pairs of vectors
    return cos_sim[np.tril_indices_from(cos_sim, k=-1)].mean()

In [53]:
get_mean_cosine_sim(dfs['response_ada_v2'])

0.8290292613560318

In [54]:
get_mean_cosine_sim(np_df_embeddings)

0.8290292613560318

In [24]:
vectors = np.array(dfs['response_ada_v2'].tolist())
vectors

array([[-0.02235282, -0.03829408, -0.01292331, ..., -0.01967299,
        -0.01066925, -0.04012238],
       [-0.02713806, -0.02515924,  0.00655965, ..., -0.00756833,
        -0.01453274, -0.04528149],
       [-0.01141089, -0.01900526, -0.00268994, ..., -0.01612997,
         0.02228025, -0.01765142],
       [-0.0080207 , -0.02725288,  0.00807075, ..., -0.01037937,
         0.01024173, -0.03165738],
       [-0.02713806, -0.02515924,  0.00655965, ..., -0.00756833,
        -0.01453274, -0.04528149]])

In [16]:
vectors.shape

(5, 1536)

In [19]:
# average across all vectors
vmean = vectors.mean(axis=0)
vmean.shape

(1536,)

In [20]:
# calculate cosine similarity between v1 and all vectors in vectors
cos_sim = cosine_similarity(vmean.reshape(1, -1), vectors)

# get index of closest vector
closest_idx = cos_sim.argmax()

print(closest_idx)

1

In [ ]:
# get all embeddings (possibly done above)

In [ ]:
# actuals variables
hcol = [
    # id
    # 'w2_ResponseId', 

# gender
'w2_actual_gender', # keep male female only

# big 5
'w2_actual_open','w2_actual_concientious', 
'w2_actual_extravert', 'w2_actual_agreeable',
'w2_actual_neurotic', 

# keep categories
'w2_actual_race', 'w2_actual_education',
    
# convert to quintiles and save labels of midpoints
'w2_actual_SDO', 'w2_actual_conservative', # 5 point scale
'w2_actual_income', 'w2_actual_age',
'w2_actual_weight', 'w2_actual_height'
]

In [ ]:
# create quintiles of numeric variables

In [ ]:
# for each attribute
# for each level

In [21]:
cos_sim

array([[0.93721715, 0.95036267, 0.87802806, 0.92952031, 0.95036267]])

In [ ]:
# calculate cosine similarity between all vectors in vectors with the vmean
cos_sim = cosine_similarity(vectors, vmean.reshape(1, -1))

In [18]:
vmean.reshape(1, -1).shape

(1, 1536)

In [34]:
cos_sim = cosine_similarity(vectors)

In [ ]:
#

In [1]:
# test aggregation on column of vectors
dfs[['model','response_ada_v2']].groupby('model').response_ada_v2.agg(lambda x: get_mean_cosine_sim(x))

NameError: name 'dfs' is not defined

In [32]:
dfs.groupby('model').apply(get_mean_cosine_sim, col='response_ada_v2')

C:\Users\niswitan\AppData\Local\Temp\ipykernel_17392\1545653399.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfs.groupby('model').apply(get_mean_cosine_sim, col='response_ada_v2')

ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [19]:
cos_sim

array([[1.        , 0.84115586, 0.77392315, 0.8975988 , 0.84115586],
       [0.84115586, 1.        , 0.75798983, 0.81575538, 1.        ],
       [0.77392315, 0.75798983, 1.        , 0.78896851, 0.75798983],
       [0.8975988 , 0.81575538, 0.78896851, 1.        , 0.81575538],
       [0.84115586, 1.        , 0.75798983, 0.81575538, 1.        ]])

In [20]:
# mean of values of lower triangle of cos_sim
cos_sim_df.values[np.tril_indices_from(cos_sim_df.values, k=-1)].mean()

0.8290292613560318

In [27]:
# mean of values of lower triangle of cos_sim
cos_sim[np.tril_indices_from(cos_sim, k=-1)].mean()

0.8290292613560318

In [21]:
import numpy as np

# extract the lower triangle of the array
lower_triangle = np.tril(cos_sim)

# calculate the average of the values in the lower triangle
avg_lower_triangle = np.mean(lower_triangle)

print(avg_lower_triangle)

0.5316117045424128

In [ ]:
# given set of vectors, calculate the cosine similarities between all pairs
from scipy.spatial.distance import pdist, squareform
from sklearn.metrics.pairwise import cosine_similarity
dfs['response_ada_v2'] = dfs['response_ada_v2'].apply(lambda x: np.array(x))
dfs['response_ada_v2'] = dfs['response_ada_v2'].apply(lambda x: x.reshape(1,-1))
dfs['response_ada_v2'] = dfs['response_ada_v2'].apply(lambda x: x[0])
dfs['response_ada_v2']

In [16]:
dfs['response_tsne_comp'] = dfs["response_ada_v2"].apply(
    lambda x : tsne_components_from_embeddings(x)
    )

ValueError: Expected 2D array, got 1D array instead:
array=[-0.02235282 -0.03829408 -0.01292331 ... -0.01967299 -0.01066925
 -0.04012238].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.