In [2]:
question_format_lambdas = [
    lambda q: f'{q} \n', # 0
    lambda q: f'<|im_start|>\n{q} \n<|im_end|>\n', # 0 - ChatGPT style
    lambda q: f'Question: {q} \nAnswer: ', # 1
    lambda q: f'Q: {q} \nA: ', # 2
    lambda q: f'Provide an answer to the following question: \n{q} \n', # 3
    lambda q: f'Provide an answer to the following question: \n{q} \nAnswer: ', # 4
    # lambda q: f'Provide an answer to the following "get-to-know-you" question: \n{q} \nAnswer: ',
    lambda q: f'Provide a short answer to the following question: \n{q} \nAnswer: ', # 6
    ]
    
question = 'Are drag queens dangerous?'    

def format_question(question, format=lambda q: f'Q: {q} \n'):
    return format(question)

print(format_question(question, question_format_lambdas[1]))

<|im_start|>
Are drag queens dangerous?
<|im_end|>

In [2]:
# for qform in question_format_lambdas:
#     print(format_question(question, qform))
#     print('--------------')

In [3]:
# prompt = format_question(question, qform)
# print(prompt)

In [3]:
# get questions
import pandas as pd


# load questions
questions = pd.read_csv('all_questions.csv')

# question indices
qix = list(range(questions.shape[0]))

# from random import sample
# sample questions
# qix_sample = sample(qix, 50) # about 10 per question category
# print(qix_sample[:10])

# # save sample
# import pickle
# with open('qix_sample.pkl','wb') as f:
#     pickle.dump(qix_sample, f)

# # with open('qix_sample.pkl','rb') as f:
# #     qix_sample = pickle.load(f)

In [4]:
questions[questions.question=="What is the best piece of advice anyone has given you?"]

     newID                                           question
693  258-2  What is the best piece of advice anyone has gi...

In [84]:
# questions.iloc[1639,:]
questions['question'][693]

'What is the best piece of advice anyone has given you?'

### Collect results from ChatGPT via AugLoop OpenAI API

In [1]:
# import pickle

# with open('qix_sample.pkl','rb') as f:
#     qix_sample = pickle.load(f)

In [2]:
!ls

'0 setup.ipynb'
'0 setup.ipynb.amltmp'
'Wave 1 Data.xlsx'
 ai-responses.zip
 all_questions.csv
'assess question formatting.ipynb'
'assess question formatting.ipynb.amltmp'
'babel setup.ipynb'
'babel setup.ipynb.amltmp'
'collect responses - babel.ipynb'
'collect responses - babel.ipynb.amltmp'
'collect responses - huggingface - final.ipynb.amltmp'
'collect responses - huggingface fb opt 1.3 - final.ipynb'
'collect responses - huggingface fb opt 1.3 - final.ipynb.amltmp'
'collect responses - huggingface fb opt iml 1.3 - final.ipynb'
'collect responses - huggingface fb opt iml 1.3 - final.ipynb.amltmp'
'collect responses - huggingface fb opt.ipynb'
'collect responses - huggingface fb opt.ipynb.amltmp'
'collect responses - huggingface gpt2-xl - final.ipynb'
'collect responses - huggingface gpt2-xl - final.ipynb.amltmp'
'collect responses - openai - final.ipynb'
'collect responses - openai - final.ipynb.amltmp'
'collect responses - openai api.ipynb'
'collect responses - openai api.ipynb.amltmp'
'collect responses - openai chatgpt - final.ipynb'
'collect responses - openai chatgpt - final.ipynb.amltmp'
'collect responses.ipynb.amltmp'
 gpt3-qform0-sample-responses.csv
 gpt3-responses-interim-max30.csv
 gpt3-responses-interim-test.csv
 gpt3-responses-interim.csv
 gpt3-responses-max30.csv
 gpt3-responses-qform0-sample.csv
 gpt3-responses-test.csv
 gpt3-responses.csv
 hf-fbopt1.3-responses-interim-max30.csv
 hf-fbopt1.3-responses-interim.csv
 hf-fbopt1.3-responses-max30.csv
 hf-fbopt1.3-responses.csv
 hf-fboptiml1.3-responses-interim-max30.csv
 hf-fboptiml1.3-responses-interim.csv
 hf-fboptiml1.3-responses-max30.csv
 hf-fboptiml1.3-responses.csv
 hf-gpt2xl-responses-interim-max30.csv
 hf-gpt2xl-responses-interim.csv
 hf-gpt2xl-responses-max30.csv
 hf-gpt2xl-responses.csv
 hf-qform-responses-for-review-annotated.csv
 hf-qform-responses-interim.csv
 hf-qform-responses.csv
 hf-responses-interim.csv
 llmclient.py
 llmclient.py.amltmp
'load prompts test.ipynb'
'load prompts test.ipynb.amltmp'
 max30responses.zip
 qix_sample.pkl
 responses-for-review-2.csv

In [2]:
# %pip install msal

Collecting msal
  Downloading msal-1.21.0-py2.py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2.0.0 in /anaconda/envs/py38_PT/lib/python3.8/site-packages (from msal) (2.28.2)
Collecting PyJWT[crypto]<3,>=1.0.0
  Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
Collecting cryptography<41,>=0.6
  Downloading cryptography-39.0.2-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 59.0 MB/s eta 0:00:00:00:01
Requirement already satisfied: cffi>=1.12 in /anaconda/envs/py38_PT/lib/python3.8/site-packages (from cryptography<41,>=0.6->msal) (1.15.1)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda/envs/py38_PT/lib/python3.8/site-packages (from requests<3,>=2.0.0->msal) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /anaconda/envs/py38_PT/lib/python3.8/site-packages (from requests<3,>=2.0.0->msal) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in /anaconda/envs/py38_PT/lib/python3.8/site-packages (from requests<3,>=2.0.0->msal) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /anaconda/envs/py38_PT/lib/python3.8/site-packages (from requests<3,>=2.0.0->msal) (3.4)
Requirement already satisfied: pycparser in /anaconda/envs/py38_PT/lib/python3.8/site-packages (from cffi>=1.12->cryptography<41,>=0.6->msal) (2.21)
Installing collected packages: PyJWT, cryptography, msal
Successfully installed PyJWT-2.6.0 cryptography-39.0.2 msal-1.21.0
Note: you may need to restart the kernel to use updated packages.

In [12]:
# from llmclient import LLMClient

In [13]:
# llm_client = LLMClient()

In [15]:
# request_data = {
#         "prompt":"Seattle is",
#         "max_tokens":50,
#         "temperature":1,
#         "top_p":1,
#         "n":5,
#         "stream":False,
#         "logprobs":None,
#         "stop":"\n"
# }

# # get the model response
# # available models are:
# # text-davinci-001 (GPT-3)
# # text-davinci-002 (GPT-3.5)
# # text-davinci-003 (GPT-3.51)
# # text-chat-davinci-002 (ChatGPT)
# response = llm_client.send_request('text-chat-davinci-002', request_data)
# print(response)

In [11]:
# import json
# import requests
# # get the token
# token = llm_client._get_token()

# # populate the headers
# headers = {
#     'Content-Type':'application/json', 
#     'Authorization': 'Bearer ' + token, 
#     'X-ModelType': 'text-chat-davinci-002' }

# body = str.encode(json.dumps(request_data))
# response = requests.post(LLMClient._ENDPOINT, 
#     json=request_data, 
#     #data=body,
#     headers=headers)

KeyboardInterrupt:

In [62]:
print(response.json())

{'id': 'cmpl-6qBYvhVu3yqcOYsBFimZU1pEXWZSd', 'object': 'text_completion', 'created': 1677895521, 'model': 'davinci', 'choices': [{'text': ' a very vibrant place for design and we have to make sure that we translate that into our visual elements. So, we are going to take a page from the innovation of Amazon, and make our logo modern, sleek and visually engaging.', 'index': 0, 'logprobs': None, 'finish_reason': 'stop'}, {'text': ' in the midst of a significant population boom. According to data from King County, the population in Seattle increased by over 24% between 2010 and 2018, and the county has gained more than 400,000 residents since 2010.', 'index': 1, 'logprobs': None, 'finish_reason': 'stop'}, {'text': ' more profitable than either Boston or San Francisco.', 'index': 2, 'logprobs': None, 'finish_reason': 'stop'}, {'text': ' host to multiple games throughout the tournament, including the opening match between teams United States and Australia. Mayor Tim Burgess and Washington State Convention Center, who organized the tournament, highlighted the women players an inspiration to young girls and future leaders everywhere.', 'index': 3, 'logprobs': None, 'finish_reason': 'stop'}, {'text': ' a beautiful city due to its natural setting and interesting contrast of old and new construction. It could be to unique places found in Seattle such as Pike Place Market, Space Needle and Pacific Science Center are worth visiting. The city also has wonderful parks such', 'index': 4, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 2, 'completion_tokens': 197, 'total_tokens': 199}}

In [4]:
import requests
import json
import pandas as pd
import datetime

questions = pd.read_csv('all_questions.csv')

In [81]:
endpoint = LLMClient._ENDPOINT
deployment_name = "text-chat-davinci-002" 
token = llm_client._get_token()

In [82]:
headers = {
    'Content-Type':'application/json', 
    'Authorization': 'Bearer ' + token, 
    'X-ModelType': 'text-chat-davinci-002' 
    }

In [42]:
def create_question_body(question, max_token_length=100, format=lambda q: f'{q} \n', stop=None):
    prompt = format_question(question, format)
    body = {
        'prompt':prompt, # get more "personal" answers here
        'max_tokens':max_token_length,
        'temperature':0.75,
        # 'top_p':, # use this or temperature, not both; lower values closer to greedy search
        'n': 4,
        'stop':stop,
        'presence_penalty':0,
        'frequency_penalty':0,
        'stream':False,
        'logprobs':None,
    }
    return body, prompt

In [28]:
import time
# time.sleep(3)

In [85]:
question = "When did global warming begin?"

qform = lambda q: f'{q} \n'  # format "0"

max_token_length = 30

body,prompt = create_question_body(question, max_token_length, format=qform)

In [86]:
resp = requests.post(
    endpoint,
    headers=headers,
    json=body,
    )

KeyboardInterrupt:

In [79]:
print(resp.json()['choices'][0]['text'])

The main causes of global warming are the burning of fossil fuels such as coal, oil, and gas, deforestation, and agriculture. These activities release

In [30]:
# errorResponses = []
# errorResponseString = json.dumps(resp.json())
# errorResponses.append((i, newID, errorResponseString))
# errorResponses

[(1639,
  '243-4',
  '{"error": {"message": "The response was filtered due to the prompt triggering Azure OpenAI\\u2019s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", "type": null, "param": "prompt", "code": "content_filter", "status": 400}}')]

In [80]:
# initialize dataframe for collecting results
responsesDF = pd.DataFrame({})

# choose question format
qform = lambda q: f'{q} \n'  # format "0"

max_token_length = 30

errorResponses = []

# for i in range(questions.shape[0]):
# for i in qix:
for i in range(693,questions.shape[0]):
    newID = questions['newID'][i]
    question = questions['question'][i]
    print(question)

    # create API request body and formatted prompt from question
    body,prompt = create_question_body(question, max_token_length, qform)
    # submit request to API
    resp = requests.post(
        endpoint,
        headers=headers,
        json=body,
        )

    try:
        createdDate = datetime.datetime.fromtimestamp(resp.json()['created'])
        modelName = resp.json()['model']
    # except JSONDecodeError:
    #     print('getting new token')
    #     time.sleep(10)
    #     token = llm_client._get_token()
    #     headers = {
    #         'Content-Type':'application/json', 
    #         'Authorization': 'Bearer ' + token, 
    #         'X-ModelType': 'text-chat-davinci-002' 
    #         }
    except:
        errorResponseString = json.dumps(resp.json())
        print(errorResponseString)
        errorResponses.append((i, newID, errorResponseString))
        continue

    print(resp.json()['choices'][0]['text'])
    
    # collect responses data into dataframe
    data = {
        'newID':newID,
        'modelID':'openai/ChatGPT',
        'formatID':0,
        'question':question,
        'prompt':prompt,
        'created':createdDate,
        'model':modelName,
        'response_index':[completion['index'] for completion in resp.json()['choices']],
        'response':[completion['text'] for completion in resp.json()['choices']],
    }
    respDF = pd.DataFrame(data)

    # append to file
    respDF.to_csv('ChatGPT-responses-interim-max30.csv', header=False, index=False, mode='a')    
    # add to overall results dataframe
    responsesDF = pd.concat([responsesDF, respDF])
    #if i % 10 == 0: print(f"{i}: {newID}: {question}")
    time.sleep(10)

# write to file
responsesDF.to_csv('ChatGPT-responses-max30.csv', index=False)

How do you feel about your current employer?
- Why did you leave your last job?
- How do you manage your workload and prioritize tasks?
- How do you handle stress
Is you job particularly satisfying?
Is the pay good?

What do you do?

I am a software engineer. I work primarily on developing and maintaining software systems for
Do you feel your work encroaches on your person life?

It can be difficult to separate my work life from my personal life, especially when I am working on a big project or deadline. However, I
What advice would you give a new employee trying to make a good impression on their first day?

1. Come prepared for your first day on the job by doing your research on the company, the role you'll be taking on, and the
What is something that motivates you in life?

There are many things that motivate me in life, but perhaps the most powerful is the desire to make a positive impact on the world and the people
What's the best piece of advice you've received?

There's a lot of great advice I've received over the years, but one piece that comes to mind is to always be true to yourself.
If you could stop working right now and retire, would you do it?

I enjoy my work, so I would likely continue working in some capacity even after retirement. However, I would also have plenty of time to enjoy
What's the best way to balance your time?

The best way to balance your time is to prioritize your tasks, set clear goals and deadlines, and allocate your time appropriately. Additionally, it is
What piece of advice given to you has been most helpful to your career?

The most helpful piece of advice I have received in my career was to always be true to yourself and stay authentic. It’s important to
What would your 65 year old self tell your 25 year old self about life and work?

My 65 year old self would tell my 25 year old self that life is a journey full of ups and downs, but to always keep a positive
do you spend more time at work than necessary

- do you feel overwhelmed by the amount of work you have
- do you feel drained or exhausted after work
- do you often
what's the best thing to do when balancing life and work

One strategy for balancing life and work is to set clear boundaries and priorities. This may include creating a schedule or to-do list that allocates
Do you like your job or only do it for the money
-I like my job, the money is just a bonus

Do you believe in love at first sight or do you think it takes time
How balanced is your life and your work?

I believe my life is quite well balanced. I make sure to prioritize my time and focus on the things that matter most to me, such as
How do you manage life between work and family?

I make sure to set aside dedicated time for both work and family. I also make sure to keep open lines of communication and make sure that everyone
What is the biggest piece of advice you wish you had gotten before starting a full time job?

One of the biggest pieces of advice I wish I had gotten before starting a full-time job is to always be aware of the company's culture
How satisfied are you with your life and career?
                        (1 = not satisfied, 10 = extremely satisfied)',
        'How often do you feel like you're living up to your full potential
How do you interact with your coworkers in a positive way?

I try to always be friendly and approachable, and I make an effort to get to know my coworkers on a personal level. I also try
What is your best advice for getting to work on time?

- Make a schedule that includes enough time for transportation, getting ready, and any other necessary tasks before leaving for work.
- Set alarms
Is you job fulfilling?
Do you like what you do?
Do you feel like you're making a difference?
Do you feel like you're doing something that's important
How do you stay productive at work?
+
+1. Set clear goals and objectives: Having a clear sense of what you need to accomplish throughout the day will help you stay focused and
How important is work/life balance?

Work-life balance is an essential aspect of overall well-being and happiness. It allows individuals to maintain a healthy balance between their professional and personal
What are things you do to have a healthy work/life balance?

- I make sure to carve out dedicated time for myself and my personal life outside of work, whether it's going for a run in the morning
What is the most important thing you have learned by working with others?

The most important thing I have learned by working with others is the importance of communication. In order to effectively collaborate and achieve a common goal, clear
What makes you passionate about your work?

What makes me passionate about my work is the impact that it can have on people's lives. It's incredibly satisfying to know that I am helping
opinion about work-life balance?

It is important for individuals to have a balance between their work and personal lives. Work can be fulfilling and provide a sense of purpose and accomplishment,
Should a person give their best work efforts on the jobs?

Yes, a person should give their best work efforts on the jobs. This is because it is not only morally right but also beneficial for the individual
What is a favorite job you have had and what is a job that you did not like so much?

My favorite job was working as a research assistant for a professor at my university. I enjoyed getting to be a part of ongoing research projects and helping
How can we manage a 40 hour work week and raise a family without being stressed?

1. Schedule and Prioritize: Create a schedule and stick to it as much as possible. Prioritize your time in order to manage
What are some tips you could give me for how to unwind after work?

1. Make time for exercise: Going for a run, taking a yoga class, or hitting the gym are all great ways to release endorph
How do you deal with a difficult co-worker or boss?

I would begin by trying to understand the root cause of their behavior. Are they under a lot of stress? Are they dealing with personal or professional
What steps do you take in your daily life to enhance your personal happiness?

I start my day with a gratitude journal, taking the time to write down the things I am grateful for. This puts me in a positive mindset
What would you tell a friend who asked you how they should go about asking for a raise?

I'd tell them to do their research, be confident and have a clear and compelling case for why they deserve a raise. Make sure to have
What is the best way to balance life and work?

There is no definitive answer to what is the best way to balance life and work, as different people have different priorities and preferences. Some common strategies
What advice would you give to yourself 5 years ago?

I would tell myself to be more confident in my abilities and not worry so much about what others think of me. I would also remind myself to
Should healthcare be universal

There are several arguments for and against universal healthcare.

Arguments for universal healthcare include the belief that healthcare is a basic human right,
What is the best piece of advice you have received over the years?

The best piece of advice I've ever received is to always be open to learning and growing, because you never know what opportunities or experiences might come
What advice did you receive that made the biggest difference in your career?

The biggest piece of advice I’ve received that has made the biggest difference in my career so far is to always be open to new opportunities
What is your work ethic?

My work ethic is based on a strong sense of responsibility and discipline. I believe in setting clear goals, creating a plan to achieve them, and
What will make people less miserable with the way we have structured work these days?

1. Flexible schedules
2. Remote work options
3. More opportunities for professional development and growth
4. Clear communication
What is the best piece of advice anyone has given you?

NameError: name 'JSONDecodeError' is not defined

In [25]:
import json
json.dumps(resp.json())

'{"error": {"message": "The response was filtered due to the prompt triggering Azure OpenAI\\u2019s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", "type": null, "param": "prompt", "code": "content_filter", "status": 400}}'

In [26]:
resp.json()['model']

KeyError: 'model'

### Merge and prepare responses with newline truncation rules
- raw
- single newline
- double newline

Also strip leading whitespace.

In [3]:
import pandas as pd

responsesDF = pd.read_csv('gpt3-qform0-sample-responses.csv')
oaidf = responsesDF.copy()

In [4]:
hfdf = pd.read_csv('hf-qform-responses-for-review-annotated.csv')

In [5]:
# restrict attention to formatID == 0
hfdf2 = hfdf[hfdf.formatID == 0]

In [6]:
# align columns
oaidf['problem?'] = None
col_list = ['newID','modelID','formatID','question','response','problem?']
oaidf2 = oaidf[col_list]
hfdf2 = hfdf2[col_list]

In [7]:
df = pd.concat([oaidf2, hfdf2])

In [69]:
len([e for e in df['problem?'] if e == 1])

7

In [48]:
# now strip leading whitespace (including newlines) from responses
df2 = df.copy()
df2['response']= [e.lstrip() for e in df2.response]

In [49]:
# now find responses that have a newline (not at the beginning, since those were stripped out)
df2['has_newline1'] = [1 * (e.find('\n') > -1) for e in df2.response]
df2['has_newline2'] = [1 * (e.find('\n\n') > -1) for e in df2.response]

In [59]:
df2_nl1 = df2[df2.has_newline1 == 1].copy()
df2_nl2 = df2[df2.has_newline2 == 1].copy()

In [40]:
tst = "1. They're the same. They're both good.\n2"
tst[:tst.find('\n')]

"1. They're the same. They're both good."

In [51]:
print(df2.shape)
print(df2_nl1.shape)
print(df2_nl2.shape)

(732, 8)
(371, 8)
(199, 8)

In [67]:
len([e for e in df2['problem?'] if e == 1])

7

In [60]:
# include truncation class
df2['truncate'] = 'none'
df2_nl1['truncate'] = 'single'
df2_nl2['truncate'] = 'double'

In [61]:
# replace response with truncated response, resetting problem coding, if any
df2_nl1['response'] = [e[:e.find('\n')] for e in df2_nl1.response]
df2_nl1['problem?'] = None
df2_nl2['response'] = [e[:e.find('\n\n')] for e in df2_nl2.response]
df2_nl2['problem?'] = None

In [62]:
# concatenate
df3 = pd.concat([df2, df2_nl1, df2_nl2])
# keep desired columns
col_list2 = col_list + ['truncate']
df3 = df3[col_list2]

In [63]:
df3.tail()

,newID,modelID,formatID,question,response,problem?,truncate
3054,460-1,gpt2-xl,0,what is your personal opinion on the overturni...,"To me, Roe vs. Wade is the law that says that ...",None,double
3094,212-1,facebook/opt-1.3b,0,What is your most controversial opinion?,I agree with Peter Thiel about a lot of things...,None,double
3109,351-4,facebook/opt-1.3b,0,How do you think the people that know you the ...,"How is the ""other side"" perceived?",None,double
3110,460-1,gpt2-xl,0,what is your personal opinion on the overturni...,"I am, and I think it is a great victory. I jus...",None,double
3147,64-5,gpt2-xl,0,What is your community like?,How do you find your work?,None,double

In [64]:
# write to file
df3.to_csv('responses-for-review-2.csv', index=False)