In [5]:
# %pip install openpyxl

In [28]:
import pandas as pd

In [29]:
op = pd.read_excel('Wave 1 Data.xlsx', sheet_name = "OpinionQ")

In [30]:
op.head()

,R_ID,category,catID,OpinionQ,newID,Order in qualtrics
0,1,opinion,1,What is your opinion on abortion?,1-1,1
1,2,opinion,1,Do you think the BLM founders deserved to buy ...,2-1,2
2,3,opinion,1,Are drag queens dangerous?,3-1,3
3,4,opinion,1,Under what conditions would you ever consider ...,4-1,4
4,5,opinion,1,Do you believe in gay marriage?,5-1,5

In [9]:
op.dtypes

R_ID                   int64
category              object
catID                  int64
OpinionQ              object
newID                 object
Order in qualtrics     int64
dtype: object

In [31]:
ad = pd.read_excel('Wave 1 Data.xlsx', sheet_name = "AdviceQ")
fa = pd.read_excel('Wave 1 Data.xlsx', sheet_name = "FactQ")
pe = pd.read_excel('Wave 1 Data.xlsx', sheet_name = "PersonalityQ")
so = pd.read_excel('Wave 1 Data.xlsx', sheet_name = "SocialQ")

In [32]:
for df in [op, ad, fa, pe, so]:
    print(df.shape)

(447, 6)
(482, 6)
(472, 6)
(492, 6)
(491, 6)

In [33]:
so.head()

,R_ID,category,catID,SocialQ,newID,Order in qualtrics
0,1,social,5,Are you in a relationship?,1-5,1
1,2,social,5,How large is your circle of friends?,2-5,2
2,3,social,5,Do you think a toxic family member is worth yo...,3-5,3
3,4,social,5,"At the end of a social gathering, how do you f...",4-5,4
4,5,social,5,Do you believe in marriage?,5-5,5

In [35]:
newIDs, questions = [], []
for df in [op, ad, fa, pe, so]: 
    newIDs.extend(df['newID'].values)
    questions.extend(df.iloc[:,3].values)
print(newIDs[:10])
print(newIDs[-10:])
assert len(newIDs) == len(set(newIDs)) # confirm unique newIDs
print(questions[:10])
print(questions[-10:])

['1-1', '2-1', '3-1', '4-1', '5-1', '6-1', '7-1', '8-1', '9-1', '10-1']
['492-5', '493-5', '494-5', '495-5', '496-5', '497-5', '498-5', '499-5', '500-5', '501-5']
['What is your opinion on abortion?', 'Do you think the BLM founders deserved to buy multi million dollar mansions?', 'Are drag queens dangerous?', 'Under what conditions would you ever consider having an abortion?', 'Do you believe in gay marriage?', 'Are you opposed to reproductive rights? why?', 'How do you feel about abortion?', 'How can abortion be right?', 'Are you pro life?', 'How do you feel about abortion rights?']
['What thing define a true family in America?', 'What is an important priority when one enters a romantic relationship?', 'How do you feel about online relationships?', 'Could you please reveal your thoughts on dating an older or much younger person?', 'Do you think young couples will be having more children in the future? It seems that liberal minded people are anti-children.', 'What types of people do you socialize with and why?', 'Do video games teach children to be violent?', 'Describe an enjoyable family gettogether.', 'Is cancel culture cyberbullying?', 'what do u think about social relationships?']

In [36]:
# put all questions with newIDs in single list
all = pd.DataFrame(data={
    'newID':newIDs,
    'question':questions,
})

In [44]:
for i in range(all.shape[0]):
    if i < 10:
        print(f"{all['newID'][i]}: {all['question'][i]}")

1-1: What is your opinion on abortion?
2-1: Do you think the BLM founders deserved to buy multi million dollar mansions?
3-1: Are drag queens dangerous?
4-1: Under what conditions would you ever consider having an abortion?
5-1: Do you believe in gay marriage?
6-1: Are you opposed to reproductive rights? why?
7-1: How do you feel about abortion?
8-1: How can abortion be right?
9-1: Are you pro life?
10-1: How do you feel about abortion rights?

In [45]:
all.to_csv('all_questions.csv', index=False)

In [26]:
n_tokens = 2500 * 250 # number of questions times number of tokens returned per q
cost_per_token = .02 / 1000 # price per 1000 tokens
n_tokens * cost_per_token

12.500000000000002