In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({'cd':['ua', 'ue', 'td'], 'cd1': ['ta', 'None', 'ua'], 'cd2':['None', 'None', 'ua']})

In [5]:
df

   cd   cd1   cd2
0  ua    ta  None
1  ue  None  None
2  td    ua    ua

In [14]:
# df['all'] = df.cd + df.cd1 + df.cd2
df['all2'] = df[['cd','cd1','cd2']].apply(lambda l: ','.join(l), axis=1)
df

   cd   cd1   cd2         all          all2
0  ua    ta  None    uataNone    ua,ta,None
1  ue  None  None  ueNoneNone  ue,None,None
2  td    ua    ua      tduaua      td,ua,ua

In [22]:
df[['cd','cd1','cd2']].apply(lambda l: 1 * (sum([1 * (e in ['ua','ta']) for e in l]) > 0), axis=1)

0    1
1    0
2    1
dtype: int64

In [4]:
df['office_visit_acuity'] = df['ProcedureCD'].apply(lambda s: s[-1:])
df

   cd   cd1   cd2 cd01
0  ua    ta  None    a
1  ue  None  None    e
2  td    ua    ua    d

In [10]:
has_codes('ua')

True

In [9]:
df.apply(lambda s: has_codes(s), axis=0)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().